version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
      - redis
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=nexus_dev
      - POSTGRES_USER=nexus
      - POSTGRES_PASSWORD=nexus123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
volumes:
  postgres_data: {}
  redis_data: {}
networks:
  nexus_network:
    driver: bridge
